pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: BuildAndPublish
    displayName: 'Build and Publish to Artifactory'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      - group: be-deploy

steps:
  - task: MavenAuthenticate@0
    inputs:
      servers: 'mpsv-b2b-gw;$(MVN_REPO_USER);$(MVN_REPO_PASSWORD)'
      configFile: 'settings.xml'
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      goals: 'clean install deploy'